### ISSUE TITLE
TODO(frontend): hooks and functions waiting to develop

### ISSUE THREAD

**Issue by dongdong867** [dongdong867/go-cafe#1]
- GENERAL

  - [ ] image handler and fetcher
  - [ ] toast for notification

- Home Page

  - [ ] fetch all posts
  - [ ] search within all posts
  - [ ] post image index count

- Following List Page

  - [ ] fetch following store list

- Store Page 

  - [ ] fetch store data
  - [ ] fetch posts of store

- Store Menu Page 

  - [ ] fetch store menu

- Post At Store Page

  - [ ] fetch posts at store

- Login Page 

  - [ ] login function
  - [ ] error handler

- Sign Up Page 

  - [ ] sign up function
  - [ ] register info check
  - [ ] user/ shop role handler

- Personal Profile Page 

  - [ ] fetch user data and posts
  - [ ] fetch user status number

- Create Post Page 

  - [ ] post post function
  - [ ] post data check
  - [ ] coffee shop search function

- Update Post Page

  - [ ] fetch and display post data
  - [ ] update post data function

**Comment by dongdong867** [comment]
- login
- [ ] add clear password method when login failed
